

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:FREE
spring.datasource.username=C##DBA3R
spring.datasource.password=DBA3R
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.dialect=org.hibernate.dialect.Oracle14cDialect
#logging.level.org.hibernate=DEBUG


# JPA

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true